name: WatchBot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 36 */2 * * *
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python Scripts
      env:
        BILIBILI_NICKNAMES: ${{ secrets.BILIBILI_NICKNAMES }}
        CQHTTP_URL: ${{ secrets.CQHTTP_URL }}
        CQHTTP_TOQQ: ${{ secrets.CQHTTP_TOQQ }}
      run: |
        python bilibili_nickname.py
